### ISSUE TITLE
Docker 启动报错: java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope

### ISSUE THREAD

**Issue by Origami404** [iTXTech/mirai-console-loader#101]
Dockerfile: 
```dockerfile
FROM openjdk:11-jre

ENV TZ Asia/Shanghai

WORKDIR /app

RUN wget -O mcl.zip https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.2/mcl-1.2.2.zip && \ 
    unzip mcl.zip && \ 
    rm mcl.zip

RUN chmod +x mcl && \
    ./mcl --update-package net.mamoe:mirai-core-all --channel stable --type plugin && \
    ./mcl --update-package net.mamoe:mirai-api-http --channel stable-v2 --type plugin && \
    ./mcl --dry-run

EXPOSE 8080

CMD ["./mcl"]
```

构建后多次运行, 均报错: 

```
mirai-docker-mirai-http-1  |   16:45:56 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
mirai-docker-mirai-http-1  |   16:45:56 [INFO] https://github.com/iTXTech/mirai-console-loader
mirai-docker-mirai-http-1  |   16:45:56 [INFO] This program is licensed under GNU AGPL v3
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Fetching Mirai Console Loader Announcement...
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Mirai Console Loader Announcement:
mirai-docker-mirai-http-1  | Mirai Console Loader 公告栏
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  | 如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
mirai-docker-mirai-http-1  | `- 如 Unsupported image type for ExternalResource *
mirai-docker-mirai-http-1  | `  considering use gif/png/bmp/jpg format.
mirai-docker-mirai-http-1  | `- Tracker: https://github.com/mamoe/mirai/issues/new/choose
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  | 常用资源整合
mirai-docker-mirai-http-1  | `- https://mirai.mamoe.net/topic/653
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0-M1
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0-M1
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.1
mirai-docker-mirai-http-1  |   16:45:58 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
mirai-docker-mirai-http-1  |   16:45:58 [INFO] Verifying "net.mamoe:mirai-api-http" v2.4.0
mirai-docker-mirai-http-1  |   16:45:59 [ERROR] java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethodsRecursive(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethod0(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethod(Unknown Source)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Utility.bootMirai(Utility.java:82)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Context.call(Context.java:554)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
mirai-docker-mirai-http-1  |    at com.sun.proxy.$Proxy4.run(Unknown Source)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.start(Loader.java:176)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.main(Loader.java:68)
mirai-docker-mirai-http-1  | Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutineScope
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    ... 49 more
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1 exited with code 0
```

检查容器内 `plugins` 文件夹, 三个 jar 文件的 `sha1sum` 计算结果均与 `*.sha1` 相同:
```
$ sha1sum mcl-addon-1.2.2.jar && cat mcl-addon-1.2.2.sha1
21df4b357d858b81d2707492cf670018747aa1b0  mcl-addon-1.2.2.jar
21df4b357d858b81d2707492cf670018747aa1b0
                                                                                                                                                                                  
$ sha1sum mirai-core-all-2.10.1.jar && cat mirai-core-all-2.10.1.sha1 
47e819998633084c98d851d77422cf367999cbe8  mirai-core-all-2.10.1.jar
47e819998633084c98d851d77422cf367999cbe8
                                                                                                                                                                                  
$ sha1sum mirai-api-http-2.4.0.jar && cat mirai-api-http-2.4.0.sha1 
0c5d7411746c9ba569af28f5b3114125fa789a87  mirai-api-http-2.4.0.jar
0c5d7411746c9ba569af28f5b3114125fa789a87                                                         
```

已按照 [Mirai-http 开始使用](https://github.com/project-mirai/mirai-api-http#%E5%BC%80%E5%A7%8B%E4%BD%BF%E7%94%A8) 一节写入配置文件.

**Comment by cssxsh** [comment]
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0-M1
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0-M1
mirai-docker-mirai-http-1  |   16:45:57 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.1

版本不一致？

**Comment by Origami404** [comment]
原来 mirai-console-* 包默认的 channel 不是 stable 吗...

在修改了 Dockerfile 指定了各个包的 channel 之后再次运行, 现在报了第二个错误:

```
mirai-docker-mirai-http-1  |   21:57:13 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
mirai-docker-mirai-http-1  |   21:57:13 [INFO] https://github.com/iTXTech/mirai-console-loader
mirai-docker-mirai-http-1  |   21:57:13 [INFO] This program is licensed under GNU AGPL v3
mirai-docker-mirai-http-1  |   21:57:13 [INFO] Fetching Mirai Console Loader Announcement...
mirai-docker-mirai-http-1  |   21:57:13 [INFO] Mirai Console Loader Announcement:
mirai-docker-mirai-http-1  | Mirai Console Loader 公告栏
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  | 如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
mirai-docker-mirai-http-1  | `- 如 Unsupported image type for ExternalResource *
mirai-docker-mirai-http-1  | `  considering use gif/png/bmp/jpg format.
mirai-docker-mirai-http-1  | `- Tracker: https://github.com/mamoe/mirai/issues/new/choose
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  | 常用资源整合
mirai-docker-mirai-http-1  | `- https://mirai.mamoe.net/topic/653
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1  |   21:57:13 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
mirai-docker-mirai-http-1  |   21:57:14 [INFO] Verifying "net.mamoe:mirai-console" v2.10.1
mirai-docker-mirai-http-1  |   21:57:14 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.1
mirai-docker-mirai-http-1  |   21:57:14 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.1
mirai-docker-mirai-http-1  |   21:57:14 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
mirai-docker-mirai-http-1  |   21:57:14 [INFO] Verifying "net.mamoe:mirai-api-http" v2.4.0
mirai-docker-mirai-http-1  |   21:57:14 [ERROR] java.lang.NoClassDefFoundError: net/mamoe/mirai/console/MiraiConsoleImplementation
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethodsRecursive(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethod0(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.Class.getMethod(Unknown Source)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Utility.bootMirai(Utility.java:82)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.Context.call(Context.java:554)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
mirai-docker-mirai-http-1  |    at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
mirai-docker-mirai-http-1  |    at com.sun.proxy.$Proxy4.run(Unknown Source)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.start(Loader.java:176)
mirai-docker-mirai-http-1  |    at org.itxtech.mcl.Loader.main(Loader.java:68)
mirai-docker-mirai-http-1  | Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.MiraiConsoleImplementation
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
mirai-docker-mirai-http-1  |    ... 40 more
mirai-docker-mirai-http-1  | 
mirai-docker-mirai-http-1 exited with code 0
``` 

我查阅了本 repo 跟 mirai 的 issue, 看到 #23 有类似报错, 原因似乎仍为版本冲突. 其是通过将 channel 全设置为 nightly 来解决该问题. 那么是否将各插件的 channel 全设置为 stable 亦能解决该问题? 我是否仍有插件的 channel 未设置?  

修改后的 Dockerfile 如下:

```Dockerfile
FROM openjdk:11-jre

ENV TZ Asia/Shanghai

WORKDIR /app

# ADD ./mcl/ .
RUN wget -O mcl.zip https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.2/mcl-1.2.2.zip && \ 
    unzip mcl.zip && \ 
    rm mcl.zip

RUN chmod +x mcl && \
    ./mcl --update-package org.itxtech:mcl-addon --channel stable --type plugin && \
    ./mcl --update-package net.mamoe:mirai-console --channel stable --type plugin && \
    ./mcl --update-package net.mamoe:mirai-console-terminal --channel stable --type plugin && \
    ./mcl --update-package net.mamoe:mirai-core-all --channel stable --type plugin && \
    ./mcl --update-package net.mamoe:mirai-api-http --channel stable-v2 --type plugin && \
    ./mcl --dry-run

EXPOSE 8080

CMD ["./mcl"]
```

**Comment by cssxsh** [comment]
有点奇怪 明明已经统一版本 v2.10.1 了，居然还报错
`java.lang.ClassNotFoundException: net.mamoe.mirai.console.MiraiConsoleImplementation`

**Comment by Origami404** [comment]
合理怀疑是 console 的问题. 在删去 mirai-console-* 与 mirai-core-all 后成功运行. 

成功运行的 Dockerfile:

```
FROM openjdk:11-jre

ENV TZ Asia/Shanghai

WORKDIR /app

# ADD ./mcl/ .
RUN wget -O mcl.zip https://github.com/iTXTech/mirai-console-loader/releases/download/v1.2.2/mcl-1.2.2.zip && \ 
    unzip mcl.zip && \ 
    rm mcl.zip

RUN chmod +x mcl && \
    ./mcl --update-package net.mamoe:mirai-api-http --channel stable-v2 --type plugin && \
    ./mcl --dry-run

EXPOSE 8080

CMD ["./mcl"]
```

成功运行后的 `plugins` 目录:

```
$ tree .
.
├── mcl-addon-1.2.2.jar
├── mcl-addon-1.2.2.sha1
├── mirai-api-http-2.4.0.jar
└── mirai-api-http-2.4.0.sha1

0 directories, 4 files
```
