### ISSUE TITLE
MCL启动报错E/MCL Addon: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by StirrerCymbal5zn** [iTXTech/mirai-console-loader#102]
且INITIAL KEY在日志中不会报告
root@iugiu72023:~/mirai# ./mcl -x 2.0-RC
  08:26:34 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  08:26:34 [INFO] https://github.com/iTXTech/mirai-console-loader
  08:26:34 [INFO] This program is licensed under GNU AGPL v3
  08:26:35 [INFO] Verifying "net.mamoe:mirai-console" v2.0-RC
  08:26:38 [WARN] Package "net.mamoe:mirai-console" has newer version "2.10.1"
  08:26:38 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.0-RC
  08:26:38 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.10.1"
  08:26:38 [INFO] Verifying "net.mamoe:mirai-core-all" v2.0-RC
  08:26:39 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.10.1"
  08:26:39 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  08:26:39 [INFO] Verifying "net.mamoe:mirai-api-http" v2.4.0
  08:26:40 [WARN] Run ./mcl -u to update packages.
  08:26:40 [INFO] Fetching Mirai Console Loader Announcement...

2022-03-13 08:26:42 I/main: Starting mirai-console...
2022-03-13 08:26:42 I/main: Backend: version 2.0-RC, built on 2021-01-12 11:08:10.
2022-03-13 08:26:42 I/main: Frontend Terminal: version 2.0-RC, provided by Mamoe Technologies
2022-03-13 08:26:42 I/plugin: Successfully loaded plugin MCL Addon
2022-03-13 08:26:42 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2022-03-13 08:26:43 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2022-03-13 08:26:43 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-03-13 08:26:43 E/MCL Addon: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.processAnnotationArguments(ReflectKotlinClass.kt:176)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.processAnnotation(ReflectKotlinClass.kt:165)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.loadMethodAnnotations(ReflectKotlinClass.kt:100)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectClassStructure.visitMembers(ReflectKotlinClass.kt:90)
	at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.ReflectKotlinClass.visitMembers(ReflectKotlinClass.kt:71)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadAnnotationsAndInitializers(AbstractBinaryClassAnnotationAndConstantLoader.kt:304)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.access$loadAnnotationsAndInitializers(AbstractBinaryClassAnnotationAndConstantLoader.kt:40)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader$storage$1.invoke(AbstractBinaryClassAnnotationAndConstantLoader.kt:45)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader$storage$1.invoke(AbstractBinaryClassAnnotationAndConstantLoader.kt:40)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:532)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:607)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.findClassAndLoadMemberAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.kt:167)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.findClassAndLoadMemberAnnotations$default(AbstractBinaryClassAnnotationAndConstantLoader.kt:152)
	at kotlin.reflect.jvm.internal.impl.load.kotlin.AbstractBinaryClassAnnotationAndConstantLoader.loadCallableAnnotations(AbstractBinaryClassAnnotationAndConstantLoader.kt:98)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer$getAnnotations$1.invoke(MemberDeserializer.kt:374)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.MemberDeserializer$getAnnotations$1.invoke(MemberDeserializer.kt:27)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:375)
	at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:494)
	at kotlin.reflect.jvm.internal.impl.storage.StorageKt.getValue(storage.kt:42)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.getAnnotations(DeserializedAnnotations.kt)
	at kotlin.reflect.jvm.internal.impl.serialization.deserialization.descriptors.DeserializedAnnotations.iterator(DeserializedAnnotations.kt:32)
	at kotlin.reflect.jvm.internal.UtilKt.computeAnnotations(util.kt:257)
	at kotlin.reflect.jvm.internal.KCallableImpl$_annotations$1.invoke(KCallableImpl.kt:36)
	at kotlin.reflect.jvm.internal.KCallableImpl$_annotations$1.invoke(KCallableImpl.kt:23)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92)
	at kotlin.reflect.jvm.internal.KCallableImpl.getAnnotations(KCallableImpl.kt:38)
	at net.mamoe.mirai.console.internal.command.CompositeCommandSubCommandAnnotationResolver.hasAnnotation(CommandReflector.kt:311)
	at net.mamoe.mirai.console.internal.command.CommandReflector.isSubCommandFunction(CommandReflector.kt:118)
	at net.mamoe.mirai.console.internal.command.CommandReflector.access$isSubCommandFunction(CommandReflector.kt:106)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$1.invoke(CommandReflector.kt:232)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$1.invoke(CommandReflector.kt:106)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:773)
	at net.mamoe.mirai.console.internal.command.CommandReflector.findSubCommands(CommandReflector.kt:285)
	at net.mamoe.mirai.console.command.CompositeCommand$overloads$2.invoke(CompositeCommand.kt:99)
	at net.mamoe.mirai.console.command.CompositeCommand$overloads$2.invoke(CompositeCommand.kt:85)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.console.command.CompositeCommand.getOverloads(CompositeCommand.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:75)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at org.itxtech.mcl.addon.Addon.<init>(Addon.kt:57)
	at org.itxtech.mcl.addon.PluginMain.onEnable(PluginMain.kt:50)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:204)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
	at org.itxtech.mcl.Loader.start(Loader.java:176)
	at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.annotation.IncompleteAnnotationException: net.mamoe.mirai.console.command.CompositeCommand$SubCommand missing element value
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:83)
	at net.mamoe.mirai.console.command.$Proxy15.value(Unknown Source)
	... 96 more

2022-03-13 08:26:43 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-03-13 08:26:43 E/net.mamoe.mirai-api-http: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/MiraiLogger$Factory
java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/MiraiLogger$Factory
	at net.mamoe.mirai.api.http.MahPluginImpl.<clinit>(MahPluginImpl.kt:27)
	at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:48)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:204)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
	at org.itxtech.mcl.Loader.start(Loader.java:176)
	at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.utils.MiraiLogger$Factory
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 43 more

2022-03-13 08:26:43 I/main: 2 plugin(s) enabled.
2022-03-13 08:26:43 I/main: mirai-console started successfully.

**Comment by StirrerCymbal5zn** [comment]
MCL启动后尝试使用手动启动Mirai Console则会报告
2022-03-13 08:32:13 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-03-13 08:32:13 E/net.mamoe.mirai-api-http: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/MiraiLogger$Factory
java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/MiraiLogger$Factory
	at net.mamoe.mirai.api.http.MahPluginImpl.<clinit>(MahPluginImpl.kt:27)
	at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:48)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:204)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.utils.MiraiLogger$Factory
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 13 more

2022-03-13 08:32:13 I/main: 2 plugin(s) enabled.
2022-03-13 08:32:13 I/main: mirai-console started successfully.
> 

环境
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by PeratX** [comment]
第一个问题，尝试禁用MCL Addon
第二个问题，请上传config.json写出调查

**Comment by PeratX** [comment]
顺便，mirai版本太久了，插件可能不兼容，尝试移除config.json后重试安装mirai-api-http
