### ISSUE TITLE
Fail to start mcl in Ubuntu

### ISSUE THREAD

**Issue by xzwj1699** [iTXTech/mirai-console-loader#103]
error log:

13:28:23 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
 13:28:23 [INFO] https://github.com/iTXTech/mirai-console-loader
 13:28:23 [INFO] This program is licensed under GNU AGPL v3
 13:28:23 [INFO] Fetching Mirai Console Loader Announcement...
 13:28:24 [INFO] Mirai Console Loader Announcement:
 13:28:24 [ERROR] Failed to fetch announcement.
 13:28:24 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v
 13:28:24 [ERROR] "org.bouncycastle:bcprov-jdk15on" is corrupted.
 13:28:24 [ERROR] Failed to verify package "org.bouncycastle:bcprov-jdk15on"
 13:28:24 [ERROR] TypeError: Cannot read property "channels" from null
 13:28:24 [INFO] Verifying "net.mamoe:mirai-console" v
 13:28:24 [ERROR] "net.mamoe:mirai-console" is corrupted.
 13:28:24 [ERROR] Failed to verify package "net.mamoe:mirai-console"
 13:28:24 [ERROR] TypeError: Cannot read property "channels" from null
 13:28:24 [INFO] Verifying "net.mamoe:mirai-console-terminal" v
 13:28:24 [ERROR] "net.mamoe:mirai-console-terminal" is corrupted.
 13:28:24 [ERROR] Failed to verify package "net.mamoe:mirai-console-terminal"
 13:28:24 [ERROR] TypeError: Cannot read property "channels" from null
 13:28:24 [INFO] Verifying "net.mamoe:mirai-core-all" v
 13:28:24 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
 13:28:24 [ERROR] Failed to verify package "net.mamoe:mirai-core-all"
 13:28:24 [ERROR] TypeError: Cannot read property "channels" from null
 13:28:24 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.nio.file.NoSuchFileException: libs/bcprov-jdk15on-.jar (boot.js#98)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script(boot.js:98)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.nio.file.NoSuchFileException: libs/bcprov-jdk15on-.jar
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1269)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:347)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:318)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:284)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 20 more

**Comment by PeratX** [comment]
请等待新版本发布，此问题已修复，gitee禁用raw有关。
