### ISSUE TITLE
MCL Addon 重新加载

### ISSUE THREAD

**Issue by Nambers** [iTXTech/mirai-console-loader#108]
日志:
```
D:\mirai\mclA>mcl
  18:48:47 [INFO] iTXTech Mirai Console Loader version 2.0.1-b5303b5
  18:48:47 [INFO] https://github.com/iTXTech/mirai-console-loader
  18:48:47 [INFO] This program is licensed under GNU AGPL v3
  18:48:53 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

如果无法获取Mirai-Repo信息, 例如启动时出现JSON解析错误
请升级到MCL 2.0 Beta并将 config.json 中的 Mirai-Repo 更改为 https://repo.itxtech.org

  18:48:53 [INFO] Verifying "net.mamoe:mirai-console" v2.10.3
  18:48:53 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.3
  18:48:53 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.3
  18:48:53 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  18:48:53 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2022-05-12 18:48:55 I/main: Starting mirai-console...
2022-05-12 18:48:55 I/main: Backend: version 2.10.3, built on 2022-05-08 17:33:45.
2022-05-12 18:48:55 I/main: Frontend Terminal: version 2.10.3, provided by Mamoe Technologies
2022-05-12 18:48:55 I/main: Welcome to visit https://mirai.mamoe.net/
2022-05-12 18:48:55 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-05-12 18:48:55 I/plugin: Successfully loaded plugin tech.eritquearcus.fight v1.0.2
2022-05-12 18:48:55 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-05-12 18:48:55 I/plugin: Cannot load plugin MCL Addon v1.2.2
2022-05-12 18:48:55 E/main: Failed to init MiraiConsole.
java.lang.IllegalStateException: Plugin 'MCL Addon' is already loaded and cannot be reloaded.
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:144)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:47)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:90)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:146)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:151)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:401)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
```
config.json
```json
{
  "module_packages": [
    "mcl:org.itxtech.mcl.module.builtin"
  ],
  "mirai_repo": "https://repo.itxtech.org",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": {
    "net.mamoe:mirai-console": {
      "channel": "stable",
      "version": "2.10.3",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-console-terminal": {
      "channel": "stable",
      "version": "2.10.3",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-core-all": {
      "channel": "stable",
      "version": "2.10.3",
      "type": "libs",
      "versionLocked": false
    },
    "org.itxtech:mcl-addon": {
      "channel": "c2001",
      "version": "2.0.2",
      "type": "plugins",
      "versionLocked": false
    },
    "org.bouncycastle:bcprov-jdk15on": {
      "channel": "stable",
      "version": "1.64",
      "type": "libs",
      "versionLocked": false
    }
  },
  "disabled_modules": [],
  "proxy": "",
  "log_level": 1,
  "modules_props": {}
}
```
环境: Win11

不清楚是mirai的问题还是mcl的问题

**Comment by PeratX** [comment]
您需要删除plugins目录下mcl-addon-1.2.2的文件

**Comment by Nambers** [comment]
> 您需要删除plugins目录下mcl-addon-1.2.2的文件

确实下面有两个mcl-addon 没注意到, okok
