### ISSUE TITLE
使用 maven 通道 安装 net.mamoe:mirai-logging-log4j2 到 libs 启动后有日志警告

### ISSUE THREAD

**Issue by cssxsh** [iTXTech/mirai-console-loader#111]
```log
  06:17:55 [ERROR] org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; 元素类型 "hr" 必须由匹配的结束标记 "</hr>" 终止。
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
        at org.itxtech.mcl.component.Repository.fetchMavenMetadata(Repository.java:91)
        at org.itxtech.mcl.component.Repository.getLatestVersionFromMaven(Repository.java:100)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:99)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:142)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:183)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:183)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

  06:17:55 [ERROR] Failed to verify package "net.mamoe:mirai-logging-log4j2"
  06:17:55 [ERROR] java.lang.Exception: Cannot find valid maven metadata
        at org.itxtech.mcl.component.Repository.fetchMavenMetadata(Repository.java:96)
        at org.itxtech.mcl.component.Repository.getLatestVersionFromMaven(Repository.java:100)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:99)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:142)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:183)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:183)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
```

```json
"net.mamoe:mirai-logging-log4j2": {
  "channel": "maven",
  "version": "2.11.0",
  "type": "libs",
  "versionLocked": false
},
```

**Comment by PeratX** [comment]
log level修改到0（debug）看看有没有更多信息

**Comment by cssxsh** [comment]
我自己的锅
我添加 maven_repo 的时候多加了一个 `/`,
```
"maven_repo": [
    "https://repo1.maven.org/maven2/",
    "https://maven.aliyun.com/repository/central"
  ]
```
导致最终 url 变成 `https://repo1.maven.org/maven2//net/mamoe/mirai-logging-log4j2/maven-metadata.xml`
然后回弹了 404 Not Found
不过貌似 mcl 没有跳过 404 的结果，而是继续解析了，导致不明不白的日志错误

**Comment by PeratX** [comment]
因为maven并没有重试逻辑哦
