### ISSUE TITLE
mirai-console 1.0-M4 无法启动

### ISSUE THREAD

**Issue by KevinZonda** [iTXTech/mirai-console-loader#12]
由于需要使用HttpApi所以我先配置了 `mirai-console` 为1.0-M4，但是 `.\mcl` 运行结果如下

```cmd
C:\Users\Kevin\Desktop\mcl-1.0.2>.\mcl --update-package net.mamoe:mirai-console --channel stable --version 1.0-M4
 02:20:56 [INFO] Mirai Console Loader version 1.0.2-a374eff
 02:20:56 [INFO] https://github.com/iTXTech/mirai-console-loader
 02:20:56 [INFO] This program is licensed under GNU AGPL v3
 02:20:56 [DEBUG] Loading script: boot.js
 02:20:57 [DEBUG] Loading script: config.js
 02:20:57 [DEBUG] Loading script: repo.js
 02:20:57 [DEBUG] Loading script: updater.js
 02:20:57 [INFO] Package "net.mamoe:mirai-console" has been updated.

C:\Users\Kevin\Desktop\mcl-1.0.2>.\mcl
 02:21:00 [INFO] Mirai Console Loader version 1.0.2-a374eff
 02:21:00 [INFO] https://github.com/iTXTech/mirai-console-loader
 02:21:00 [INFO] This program is licensed under GNU AGPL v3
 02:21:00 [DEBUG] Loading script: boot.js
 02:21:01 [DEBUG] Loading script: config.js
 02:21:01 [DEBUG] Loading script: repo.js
 02:21:01 [DEBUG] Loading script: updater.js
 02:21:01 [INFO] Verifying "net.mamoe:mirai-console" version 1.0-M4
 02:21:01 [INFO] "net.mamoe:mirai-console:1.0-M4" is corrupted. Start downloading...
 Downloading mirai-console-1.0-M4.jar [==============================] 13.05 MB
 Downloading mirai-console-1.0-M4.sha1 [==============================] 40 B
 02:21:14 [INFO] Verifying "net.mamoe:mirai-console-terminal" version
 02:21:14 [INFO] "net.mamoe:mirai-console-terminal:" is corrupted. Start downloading...
 Downloading mirai-console-terminal-1.0-RC-1.jar [==============================] 1.23 MB
 Downloading mirai-console-terminal-1.0-RC-1.sha1 [==============================] 40 B
 02:21:18 [INFO] Verifying "net.mamoe:mirai-core-all" version
 02:21:18 [INFO] "net.mamoe:mirai-core-all:" is corrupted. Start downloading...
 Downloading mirai-core-all-1.3.1.jar [==============================] 27.08 MB
 Downloading mirai-core-all-1.3.1.sha1 [==============================] 40 B
Exception in thread "main" java.lang.NoClassDefFoundError: net/mamoe/mirai/console/util/SemVersion
        at net.mamoe.mirai.console.terminal.ConsoleFrontEndDescImpl.<clinit>(MiraiConsoleImplementationTerminal.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.<init>(MiraiConsoleImplementationTerminal.kt:62)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.console.util.SemVersion
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 32 more
```

**Comment by PeratX** [comment]
把terminal版本也降级到M4

**Comment by KevinZonda** [comment]
> 把terminal版本也降级到M4

maven没那个包，我看了maven里面只有1.0-RC什么的

**Comment by KevinZonda** [comment]
Refer: https://mvnrepository.com/artifact/net.mamoe/mirai-console-terminal

**Comment by PeratX** [comment]
应该是mirai-console-pure，那个版本
