### ISSUE TITLE
在能正常加载的时候输入exit退出程序 第二次启动以及后续启动都会报错

### ISSUE THREAD

**Issue by LookStars** [iTXTech/mirai-console-loader#129]
[root@GreenCloud mcl]# ./mcl
  14:56:48 [INFO] iTXTech Mirai Console Loader version 2.1.0-71ec418
  14:56:48 [INFO] https://github.com/iTXTech/mirai-console-loader
  14:56:48 [INFO] This program is licensed under GNU AGPL v3
  14:56:50 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  14:56:50 [INFO] Verifying "net.mamoe:mirai-console" v2.12.0
  14:56:50 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.0
  14:56:50 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.0
  14:56:51 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  14:56:51 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2022-07-26 14:56:53 I/main: Starting mirai-console...
2022-07-26 14:56:53 I/main: Backend: version 2.12.0, built on 2022-07-03 10:57:58.
2022-07-26 14:56:53 I/main: Frontend Terminal: version 2.12.0, provided by Mamoe Technologies
2022-07-26 14:56:53 I/main: Welcome to visit https://mirai.mamoe.net/
2022-07-26 14:56:54 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-07-26 14:56:54 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-07-26 14:56:54 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin SimpleWelcome v1.1.0
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin pixiv插画 v1.7.4-future-2
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.3.3
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin bilibili-helper v1.6.1
2022-07-26 14:56:54 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2022-07-26 14:56:55 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-07-26 14:56:55 I/SimpleWelcome: Plugin loaded
2022-07-26 14:56:56 W/pixiv插画: Linked class okhttp3.Headers$Builder in bilibili-helper-1.6.1.mirai.jar but plugin not depend on it.
2022-07-26 14:56:56 W/pixiv插画: Class loading logic may change in feature.
2022-07-26 14:56:56 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-07-26 14:56:56 I/Mirai HTTP API: ********************************************************
2022-07-26 14:56:57 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2022-07-26 14:56:57 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYy0NWQlGx
2022-07-26 14:56:57 I/Mirai HTTP API: adaptors: [http]
2022-07-26 14:56:57 I/Mirai HTTP API: ********************************************************
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 更新开始
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -204800 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -409600 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -614400 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -819200 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -870400 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -1075200 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 已下载 -1090500 %
2022-07-26 14:56:57 I/AutoUpdate: pixiv-1.7.4-fix.mirai.jar 更新完成
2022-07-26 14:56:57 I/AutoUpdate: 请删除旧版本插件并重启程序
2022-07-26 14:57:01 I/bilibili-helper: 如果要B站动态的截图内容，请修改 DynamicInfo.template, 添加 #screenshot
2022-07-26 14:57:01 I/bilibili-helper: 如果要B站专栏的截图内容，请修改 Article.template, 添加 #screenshot
2022-07-26 14:57:02 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418
2022-07-26 14:57:02 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2022-07-26 14:57:02 I/main: 6 plugin(s) enabled.
2022-07-26 14:57:02 I/main: Auto-login 3321538136
2022-07-26 14:57:03 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-07-26 14:57:06 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
2022-07-26 14:57:06 W/stderr:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
2022-07-26 14:57:06 W/stderr:   at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
2022-07-26 14:57:06 W/stderr:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
2022-07-26 14:57:06 W/stderr:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:181)
2022-07-26 14:57:06 W/stderr:   at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:230)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:225)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:107)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:122)
2022-07-26 14:57:06 W/stderr:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$startState$2.invokeSuspend(NettyNetworkHandler.kt:273)
2022-07-26 14:57:06 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-07-26 14:57:06 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-07-26 14:57:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-07-26 14:57:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
2022-07-26 14:57:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-07-26 14:57:06 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-07-26 14:57:06 W/stderr: Caused by: java.util.jar.JarException: The JCE Provider file:/www/wwwroot/mirai/mcl/libs/mirai-core-all-2.12.0.jar is not signed.
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
2022-07-26 14:57:06 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
2022-07-26 14:57:06 W/stderr:   ... 39 more
2022-07-26 14:57:06 I/Bot.3321538136: Loaded account secrets from local cache.
2022-07-26 14:57:07 I/Bot.3321538136: Saved account secrets to local cache for fast login.
2022-07-26 14:57:08 I/Bot.3321538136: Login successful.
2022-07-26 14:57:11 V/Bot.3321538136: Event: BotOnlineEvent(bot=Bot(3321538136))
2022-07-26 14:57:11 I/Bot.3321538136: Bot login successful.
2022-07-26 14:57:11 I/bilibili-helper: VideoTasker with 401742377 start BiliTask(name=原神, last=2022-07-24T04:59:50.007189473+08:00, contacts=[-563996170, -965270152], cron=null)
2022-07-26 14:57:11 I/bilibili-helper: DynamicTasker with 401742377 start BiliTask(name=原神, last=2022-07-24T12:00:06+08:00, contacts=[-563996170, -965270152], cron=null)
2022-07-26 14:57:11 I/bilibili-helper: LiveWaiter with 401742377 start BiliTask(name=原神, last=2022-07-24T04:59:38.623707514+08:00, contacts=[-563996170, -965270152], cron=null)
2022-07-26 14:57:11 I/bilibili-helper: ARTICLE缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: MUSIC缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/main: mirai-console started successfully.
2022-07-26 14:57:11 I/bilibili-helper: SKETCH缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: DYNAMIC缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: VIDEO缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: LIVE缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: SEASON缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: EPISODE缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: USER缓存清理任务开始运行，间隔1h
2022-07-26 14:57:11 I/bilibili-helper: EMOJI缓存清理任务开始运行，间隔1h
> exit
Stopping mirai-console
2022-07-26 14:57:15 V/Bot.3321538136: Event: BotOfflineEvent.Active(bot=Bot(3321538136), cause=kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@4c50743d, reconnect=false)
2022-07-26 14:57:15 I/Bot.3321538136: Bot cancelled: Job was cancelled
2022-07-26 14:57:15 W/bilibili-helper: 对[-563996170]构建消息失败
java.util.concurrent.CancellationException: SelectorNetworkHandler is already closed
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:118)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:148)
        at net.mamoe.mirai.internal.message.protocol.outgoing.MessageProtocolStrategy.sendPacket$suspendImpl(MessageProtocolStrategy.kt:35)
        at net.mamoe.mirai.internal.message.protocol.outgoing.MessageProtocolStrategy.sendPacket(MessageProtocolStrategy.kt)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:105)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendAllPackets(GeneralMessageSenderProtocol.kt:89)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:68)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:260)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:311)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl$preprocessAndSendOutgoingImpl$1.invokeSuspend(MessageProtocolFacade.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-07-26 14:57:15 W/bilibili-helper: 对[-965270152]构建消息失败
java.util.concurrent.CancellationException: SelectorNetworkHandler is already closed
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:118)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:148)
        at net.mamoe.mirai.internal.message.protocol.outgoing.MessageProtocolStrategy.sendPacket$suspendImpl(MessageProtocolStrategy.kt:35)
        at net.mamoe.mirai.internal.message.protocol.outgoing.MessageProtocolStrategy.sendPacket(MessageProtocolStrategy.kt)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:105)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendAllPackets(GeneralMessageSenderProtocol.kt:89)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:68)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:260)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:311)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl$preprocessAndSendOutgoingImpl$1.invokeSuspend(MessageProtocolFacade.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

> 
mirai-console stopped successfully.
[root@GreenCloud mcl]# ./mcl
  14:57:20 [INFO] iTXTech Mirai Console Loader version 2.1.0-71ec418
  14:57:20 [INFO] https://github.com/iTXTech/mirai-console-loader
  14:57:20 [INFO] This program is licensed under GNU AGPL v3
  14:57:21 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  14:57:21 [INFO] Verifying "net.mamoe:mirai-console" v2.12.0
  14:57:22 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.0
  14:57:22 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.0
  14:57:22 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  14:57:22 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2022-07-26 14:57:24 I/main: Starting mirai-console...
2022-07-26 14:57:24 I/main: Backend: version 2.12.0, built on 2022-07-03 10:57:58.
2022-07-26 14:57:24 I/main: Frontend Terminal: version 2.12.0, provided by Mamoe Technologies
2022-07-26 14:57:24 I/main: Welcome to visit https://mirai.mamoe.net/
2022-07-26 14:57:25 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-07-26 14:57:25 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-07-26 14:57:25 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-07-26 14:57:25 E/main: Failed to init MiraiConsole.
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init0(JvmPluginClassLoader.kt:221)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt:217)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN$Companion.newLoader(JvmPluginClassLoader.kt:321)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:182)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:66)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:192)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:138)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:148)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:178)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

[root@GreenCloud mcl]#

**Comment by LookStars** [comment]
打扰了 插件问题
