### ISSUE TITLE
一个启动报错

### ISSUE THREAD

**Issue by Arturia169** [iTXTech/mirai-console-loader#140]
系统Ubuntu20.04
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  10:18:00 [INFO] Verifying "net.mamoe:mirai-console" v2.12.1
  10:18:00 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.1
  10:18:00 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.1
  10:18:01 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
2022-10-15 10:18:04 I/main: Starting mirai-console...
2022-10-15 10:18:04 I/main: Backend: version 2.12.1, built on 2022-07-31 09:49:27.
2022-10-15 10:18:04 I/main: Frontend Terminal: version 2.12.1, provided by Mamoe Technologies
2022-10-15 10:18:04 I/main: Welcome to visit https://mirai.mamoe.net/
2022-10-15 10:18:06 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-10-15 10:18:06 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-10-15 10:18:06 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-10-15 10:18:06 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2022-10-15 10:18:08 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-10-15 10:18:08 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418
2022-10-15 10:18:08 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2022-10-15 10:18:08 I/main: 1 plugin(s) enabled.
2022-10-15 10:18:08 W/WindowHelperJvm: Failed to initialize module `java.desktop`
java.lang.UnsatisfiedLinkError: /root/mcl/java/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
	at java.desktop/java.awt.Toolkit.initStatic(Unknown Source)
	at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:148)
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:92)
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:221)
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:625)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:186)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:170)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$10$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:287)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)

2022-10-15 10:18:08 I/main: Auto-login 335569218
2022-10-15 10:18:09 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

**Comment by PeratX** [comment]
HTTP connect timed out
