### ISSUE TITLE
登陆后提示当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页

### ISSUE THREAD

**Issue by chenjj100419** [iTXTech/mirai-console-loader#142]
2022-10-16 11:32:05 I/Bot.1702630800: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(1702630800), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点 击进入下载页面, errorInfo=)
2022-10-16 11:32:05 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1702630800), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1702630800), code=235, title=温馨提示, message=当前QQ版本 过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.util.concurrent.CancellationException: Bot closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
                at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
                at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
                at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                ... 4 more
        Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1702630800), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)]

**Comment by PeratX** [comment]
请汇报给mirai

**Comment by Ireinasan** [comment]
在 https://github.com/mamoe/mirai/issues/2245#issue-1368612733 中，mirai 已于 v2.13.0-RC 解决此问题，请问 mcl 如何切换 mirai 到此版本？

**Comment by buger404** [comment]
iTXTech Mirai Console Loader version 2.1.1-d66fada

  10:48:58 [INFO] Verifying "net.mamoe:mirai-console"
  10:48:58 [INFO] Updating "net.mamoe:mirai-console" to v2.12.3
 Downloading mirai-console-2.12.3-all.jar [==============================] 7.32 MB
 Downloading mirai-console-2.12.3-all.jar.sha1 [==============================] 40 B
  10:49:04 [INFO] Verifying "net.mamoe:mirai-console-terminal"
  10:49:04 [INFO] Updating "net.mamoe:mirai-console-terminal" to v2.12.3
 Downloading mirai-console-terminal-2.12.3-all.jar [==============================] 1.26 MB
 Downloading mirai-console-terminal-2.12.3-all.jar.sha1 [==============================] 40 B
  10:49:07 [INFO] Verifying "net.mamoe:mirai-core-all"
  10:49:07 [INFO] Updating "net.mamoe:mirai-core-all" to v2.12.3
 Downloading mirai-core-all-2.12.3-all.jar [==============================] 35.77 MB
 Downloading mirai-core-all-2.12.3-all.jar.sha1 [==============================] 40 B
  10:49:20 [INFO] Verifying "org.itxtech:mcl-addon"
  10:49:20 [INFO] Updating "org.itxtech:mcl-addon" to v2.0.2
 Downloading mcl-addon-2.0.2.jar [==============================] 51.64 KB
 Downloading mcl-addon-2.0.2.jar.sha1 [==============================] 40 B

也遇到了此问题，mirai已在2.13.0修复，但提供-u参数还是仅能更新至2.12.3
