### ISSUE TITLE
mcl运行报错

### ISSUE THREAD

**Issue by yimo0908** [iTXTech/mirai-console-loader#16]
系统环境：win10 家庭中文版 20H2 (19042.630)
运行环境：jre 11 x86
mcl版本：1.0.2
自动下载：mirai-console-1.0.0
                  mirai-console-terminal-1.0.0
                  mirai-core-all-1.3.1
复现步骤：powershell管理员运行指令 `java -jar mcl.jar` 到达登录步骤后按CTRL C退出
报错日志：
```
Stopping mirai-console
2020-11-23 21:30:06 W/main: Could not save Logger in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 21:30:06 W/main: Could not save settings in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.encodeSerializableValue(Encoding.kt:276)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableValue(YamlEncoder.kt:436)
        at kotlinx.serialization.internal.NullableSerializer.serialize(NullableSerializer.kt:22)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 21:30:06 I/Bot 2413448390: Bot cancelled: Job was cancelled
2020-11-23 21:30:06 W/main: Could not save AutoLogin in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:67)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 21:30:06 W/main: Could not save Logger in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 21:30:06 W/main: Could not save ExtensionSelector in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 21:30:06 W/main: Could not save PermissionService in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:61)
        at net.mamoe.mirai.console.data.AutoSavePluginData$onInit$4.invoke(AutoSavePluginData.kt:31)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:932)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:28)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1152)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by PeratX** [comment]
已支持更新到`mirai-core-all 1,3,3`
