### ISSUE TITLE
2/10 QQ服务器崩溃之后登录不上了

### ISSUE THREAD

**Issue by GarfieldF** [iTXTech/mirai-console-loader#163]
### 报错信息
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxxxx), code=
235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入
下载页面, errorInfo=        
at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLogi
nImpl.doLogin(SsoProcessor.kt:311)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLogi
nImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:
102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:664)
### 版本
2.1.2
### 协议
IPAD

**Comment by joeyandyou** [comment]
臣附议

**Comment by q2398003522** [comment]
同问题

**Comment by joeyandyou** [comment]
把mcl/bots目录下文件删掉，去config/Con…里面的Au…yml里把登录方式改成watch

**Comment by q2398003522** [comment]
好的，能登录了，谢谢
