### ISSUE TITLE
2023-03-06 09:05:27 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3022238581), code=235, title= 温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

### ISSUE THREAD

**Issue by zhaoZiQu** [iTXTech/mirai-console-loader#172]
2023-03-06 09:05:12 I/main: 7 plugin(s) enabled.
2023-03-06 09:05:12 I/main: Auto-login 3022238581, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-03-06 09:05:13 I/Bot.3022238581: Calculating type 2 PoW, it can take some time....
2023-03-06 09:05:13 I/Bot.3022238581: Got PoW result, cost: 34 ms
2023-03-06 09:05:27 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3022238581), code=235, title= 温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3022238581), code=235, title=温馨提示, message=当前QQ版本 过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by zhaoZiQu** [comment]
启动mcl 报错 提示当前QQ版本过低

**Comment by iconFehu** [comment]
一样

**Comment by PeratX** [comment]
请向mirai汇报该问题
