### ISSUE TITLE
登录QQ号提示版本过低。

### ISSUE THREAD

**Issue by Andowa** [iTXTech/mirai-console-loader#173]
Login failed: Error(bot=Bot(2035411586), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
2023-03-09 22:35:05 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2035411586), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2035411586), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by yang10560** [comment]
我也是一样的问题，应该是协议问题。别的机器人没事。希望快点修复

**Comment by q2398003522** [comment]
同问，换协议也不行了
![1](https://user-images.githubusercontent.com/25471441/224924359-82733fd8-3534-431e-99a7-9ade49c13bc2.png)

**Comment by XeronOwO** [comment]
同问，现在换协议也不行了
![1](https://user-images.githubusercontent.com/25471441/224924610-5ab1b37e-a104-4cd9-a50f-49d57626af48.png)

**Comment by cssxsh** [comment]
> 同问，现在换协议也不行了 ![1](https://user-images.githubusercontent.com/25471441/224924610-5ab1b37e-a104-4cd9-a50f-49d57626af48.png)

@Andowa @yang10560 @q2398003522 

请向mirai汇报该问题

https://github.com/mamoe/mirai

**Comment by xiaodi001-01** [comment]
这mirai的锅，不关MCL的事，毕竟MCL只是个启动mirai的启动器，你要找就找mirai(现在好像修复了，毕竟把我issue关了)
