### ISSUE TITLE
运行mcl时报错

### ISSUE THREAD

**Issue by zhongwen-4** [iTXTech/mirai-console-loader#179]
2023-07-03 11:13:47 E/Soyuz: java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpServerCodec
java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpServerCodec
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.NettyApplicationEngine$Configuration$httpServerCodec$1.<init>(NettyApplicationEngine.kt)
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.NettyApplicationEngine$Configuration$httpServerCodec$1.<clinit>(NettyApplicationEngine.kt)
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.NettyApplicationEngine$Configuration.<init>(NettyApplicationEngine.kt:79)
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.NettyApplicationEngine.<init>(NettyApplicationEngine.kt:82)
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.Netty.create(Embedded.kt:18)
        at soyuz-1.0.0-all.jar//io.ktor.server.netty.Netty.create(Embedded.kt:13)
        at soyuz-1.0.0-all.jar//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:79)
        at soyuz-1.0.0-all.jar//io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:68)
        at soyuz-1.0.0-all.jar//io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:46)
        at soyuz-1.0.0-all.jar//org.itxtech.soyuz.Soyuz.onEnable(main.kt:89)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:232)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:347)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.HttpServerCodec
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:440)
        ... 35 more

2023-07-03 11:13:47 E/JvmPluginLoader: Failed to enable 'MCL Addon' because dependencies not enabled: 'Soyuz'

**Comment by cssxsh** [comment]
soyuz-1.0.0-all.jar 不是必要的 插件，可以删掉
