### ISSUE TITLE
登录账号时报错(使用mirai-login-solver-sakura)

### ISSUE THREAD

**Issue by aahowe** [iTXTech/mirai-console-loader#180]
2023-07-11 19:27:10 I/main: Auto-login 208787712, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-07-11 19:27:11 I/Bot.208787712: Calculating type 2 PoW, it can take some time....
2023-07-11 19:27:11 I/Bot.208787712: Got PoW result, cost: 122 ms
2023-07-11 19:27:40 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(208787712), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(208787712), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)]

2023-07-11 19:27:40 I/Bot.208787712: Bot cancelled: Bot closed
2023-07-11 19:27:40 V/Bot.208787712: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@527d48db
2023-07-11 19:27:40 I/main: mirai-console started successfully.

**Comment by cssxsh** [comment]
https://mirai.mamoe.net/topic/223

**Comment by Zernca** [comment]
嗯… 无法访问此页面mirai.mamoe.net
花了太长时间进行响应
