### ISSUE TITLE
校验失败

### ISSUE THREAD

**Issue by NickJi2019** [iTXTech/mirai-console-loader#190]
11:20:14 [ERROR] Failed to verify package "org.bouncycastle:bcprov-jdk15on"
  11:20:14 [ERROR] java.net.ConnectException
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:951)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:211)
	at org.itxtech.mcl.component.Repository.httpGet(Repository.java:206)
	at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:84)
	at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
	at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
	at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
	at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:117)
	at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:190)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:190)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.net.ConnectException
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1028)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:430)
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:134)
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:94)
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:386)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:570)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:423)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:415)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:413)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:454)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:950)
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2372)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:444)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:177)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2719)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:299)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:1047)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:930)
	... 12 more
Caused by: java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:137)
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:145)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:842)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:865)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
	... 35 more

  11:20:14 [ERROR] java.nio.file.NoSuchFileException: libs/bcprov-jdk15on-.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:171)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1853)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1411)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:345)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:316)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:282)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:83)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)

**Comment by NickJi2019** [comment]
用错jdk了，从oracle jdk切换到openjdk
