### ISSUE TITLE
运行mcl时出错

### ISSUE THREAD

**Issue by HIMziyou** [iTXTech/mirai-console-loader#193]
2024-03-01 13:01:52 I/QSignService: destroy **********
2024-03-01 13:01:52 W/Bot.**********: Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.)
2024-03-01 13:01:52 V/Bot.1970450681: Event: BotOfflineEvent.Active(bot=Bot(**********), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=false)
2024-03-01 13:01:52 I/QSignService: destroy **********
2024-03-01 13:01:52 I/Bot.**********: Bot is closed manually with exception: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
java.lang.IllegalStateException: Timeout waiting for ConfigPush.
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:45)
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

>
就是正常运行一段时间以后就出现这个报错
求大佬帮忙看看

**Comment by cssxsh** [comment]
`2024-03-01 13:01:52 I/QSignService: destroy`
