### ISSUE TITLE
登陆时报错

### ISSUE THREAD

**Issue by gj1550713314** [iTXTech/mirai-console-loader#27]
2020-12-23 22:40:29 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2020-12-23 22:40:29 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2020-12-23 22:40:30 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:133)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:48)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:74)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
2020-12-23 22:40:30 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-23 22:40:30 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2020-12-23 22:40:30 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-23 22:40:30 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-23 22:40:30 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
2020-12-23 22:40:30 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
2020-12-23 22:40:30 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
2020-12-23 22:40:30 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
2020-12-23 22:40:30 W/stderr:   at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
2020-12-23 22:40:30 W/stderr:   at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
2020-12-23 22:40:30 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-12-23 22:40:30 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2020-12-23 22:40:30 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)2020-12-23 22:40:30 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2020-12-23 22:40:30 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2020-12-23 22:40:30 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-12-23 22:40:30 W/stderr: Caused by: java.util.jar.JarException: file:/E:/mcl2/libs/mirai-core-all-2.0-M1-1.jar has unsigned entries - net/mamoe/mirai/internal/AbstractBot$2.class
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
2020-12-23 22:40:30 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
2020-12-23 22:40:30 W/stderr:   ... 36 more

**Comment by PeratX** [comment]
请向mirai汇报
