### ISSUE TITLE
登录报错：Login failed: net/mamoe/mirai/utils/DefaultLoginSolver

### ISSUE THREAD

**Issue by openshell** [iTXTech/mirai-console-loader#30]
```
09:56:18 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 09:56:18 [INFO] https://github.com/iTXTech/mirai-console-loader
 09:56:18 [INFO] This program is licensed under GNU AGPL v3
 09:56:18 [DEBUG] Loading script: updater.js
 09:56:18 [DEBUG] Loading script: config.js
 09:56:18 [DEBUG] Loading script: repo.js
 09:56:18 [DEBUG] Loading script: boot.js
 09:56:19 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M1-1
 09:56:19 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M1-1
 09:56:19 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M1-1
 Downloading mirai-core-all-2.0-M2-dev-4.jar [==============================] 27.63 MB                        
 Downloading mirai-core-all-2.0-M2-dev-4.sha1 [==============================] 40 B                  
2020-12-25 09:56:44 I/main: Starting mirai-console...
2020-12-25 09:56:44 I/main: Backend: version 2.0-M1-1, built on 2020-12-19 23:26:13.
2020-12-25 09:56:44 I/main: Frontend Terminal: version 2.0-M1-1, provided by Mamoe Technologies
2020-12-25 09:56:44 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http
2020-12-25 09:56:45 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-12-25 09:56:45 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2020-12-25 09:56:45 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:32101
2020-12-25 09:56:45 I/Mirai HTTP API: Http api server is running with authKey: INITKEYkjXCMzZU
2020-12-25 09:56:45 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2020-12-25 09:56:45 I/net.mamoe.mirai-api-http: 上报模块启用状态: true
2020-12-25 09:56:45 I/main: 1 plugin(s) enabled.
2020-12-25 09:56:45 I/main: mirai-console started successfully.
> login qq password
Login failed: net/mamoe/mirai/utils/DefaultLoginSolver
2020-12-25 09:57:55 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/DefaultLoginSolver
	at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.createLoginSolver(MiraiConsoleImplementationTerminal.kt:81)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.createLoginSolver(MiraiConsoleImplementationBridge.kt:94)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:149)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
	... 23 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.utils.DefaultLoginSolver
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 29 more

```

**Comment by openshell** [comment]
昨天晚上是能登录的，今早执行`./mcl`自动更新了`mirai-core-all-2.0-M2-dev-4`，不知道是不是这个造成的。

**Comment by PeratX** [comment]
可以尝试锁定2.0-M1-1版本

**Comment by openshell** [comment]
咋锁定哟，整不来，我把config.json中的版本手动改到`2.0-M1-1`，他会自动给我改到`mirai-core-all-2.0-M2-dev-4`,求告知，谢谢！

**Comment by PeratX** [comment]
启动时添加-x启动项

**Comment by openshell** [comment]
感谢提点！我用-u参数关闭更新就行了，现在能正常登陆了。用-x还是会更新，不知道是不是哪儿弄错了，如图
![image](https://user-images.githubusercontent.com/23378811/103118280-2d65dd80-46a9-11eb-9ca1-0bef740d1c6f.png)
![image](https://user-images.githubusercontent.com/23378811/103118355-630ac680-46a9-11eb-894e-f00673390c07.png)
![image](https://user-images.githubusercontent.com/23378811/103118363-69993e00-46a9-11eb-90ca-7be910e89001.png)
![image](https://user-images.githubusercontent.com/23378811/103118368-70c04c00-46a9-11eb-8105-f046073c5eaa.png)
