### ISSUE TITLE
启动报错？

### ISSUE THREAD

**Issue by GahdWu** [iTXTech/mirai-console-loader#31]
版本：
   mcl-1.0.3

Java版本：
   openjdk version "11" 2018-09-25

系统：
   Windows 10 64位

启动日志：
`D:\Work\网络项目\qq\Release\mcl-1.0.3>mcl.cmd

 14:19:51 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 14:19:51 [INFO] https://github.com/iTXTech/mirai-console-loader
 14:19:51 [INFO] This program is licensed under GNU AGPL v3
 14:19:51 [DEBUG] Loading script: boot.js
 14:19:52 [DEBUG] Loading script: config.js
 14:19:52 [DEBUG] Loading script: repo.js
 14:19:52 [DEBUG] Loading script: updater.js
 14:19:52 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M1-1
 14:19:52 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M1-1
 14:19:52 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.3
java.lang.NoSuchMethodError: net.mamoe.mirai.utils.MiraiLogger$Companion.setDefaultLoggerCreator(Lkotlin/jvm/functions/Function1;)V
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.MiraiConsole
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)`

**Comment by openshell** [comment]
去掉中文路径，或者换版本2.0-M1-1 试试

**Comment by GahdWu** [comment]
> 去掉中文路径，或者换版本2.0-M1-1 试试

去掉中文路径还是不行，没有2.0-M1-1这个版本啊

**Comment by openshell** [comment]
> > 去掉中文路径，或者换版本2.0-M1-1 试试
> 
> 去掉中文路径还是不行，没有2.0-M1-1这个版本啊

```
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "nightly",
      "version": "2.0-M1-1",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "nightly",
      "version": "2.0-M1-1",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "nightly",
      "version": "2.0-M1-1",
      "type": "libs"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}
```
试试呢

**Comment by GahdWu** [comment]
> > > 去掉中文路径，或者换版本2.0-M1-1 试试
> > 
> > 
> > 去掉中文路径还是不行，没有2.0-M1-1这个版本啊
> 
> ```
> {
>   "js_optimization_level": -1,
>   "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
>   "maven_repo": "https://maven.aliyun.com/repository/public",
>   "packages": [
>     {
>       "id": "net.mamoe:mirai-console",
>       "channel": "nightly",
>       "version": "2.0-M1-1",
>       "type": "libs"
>     },
>     {
>       "id": "net.mamoe:mirai-console-terminal",
>       "channel": "nightly",
>       "version": "2.0-M1-1",
>       "type": "libs"
>     },
>     {
>       "id": "net.mamoe:mirai-core-all",
>       "channel": "nightly",
>       "version": "2.0-M1-1",
>       "type": "libs"
>     }
>   ],
>   "disabled_scripts": [],
>   "proxy": "",
>   "log_level": 0,
>   "script_props": {}
> }
> ```
> 
> 试试呢

卧槽！这样是不是可以了？
`GAHD@PC-20201113ZRXB MINGW64 /d/Work/NetProject/qq/Release/mcl-1.0.3
$ ./mcl.cmd
 16:18:42 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 16:18:42 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:18:42 [INFO] This program is licensed under GNU AGPL v3
 16:18:42 [DEBUG] Loading script: boot.js
 16:18:42 [DEBUG] Loading script: config.js
 16:18:42 [DEBUG] Loading script: repo.js
 16:18:42 [DEBUG] Loading script: updater.js
 16:18:42 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M1-1
 16:18:43 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M1-1
 16:18:43 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M1-1
 16:18:43 [INFO] "net.mamoe:mirai-core-all:2.0-M1-1" is corrupted. Start downloading...
 Downloading mirai-core-all-2.0-M2-dev-4.jar [==============================] 27.63 MB
 Downloading mirai-core-all-2.0-M2-dev-4.sha1 [==============================] 40 B
2020-12-25 16:18:48 I/main: Starting mirai-console...
2020-12-25 16:18:48 I/main: Backend: version 2.0-M1-1, built on 2020-12-19 23:26:13.
2020-12-25 16:18:48 I/main: Frontend Terminal: version 2.0-M1-1, provided by Mamoe Technologies
2020-12-25 16:18:48 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-12-25 16:18:48 I/main: 0 plugin(s) enabled.
2020-12-25 16:18:48 I/main: mirai-console started successfully.`

**Comment by openshell** [comment]
是的 😄

**Comment by GahdWu** [comment]
> 是的 😄

登录报这个
`Login failed: net/mamoe/mirai/utils/DefaultLoginSolver
2020-12-25 16:28:58 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/DefaultLoginSolver
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.createLoginSolver(MiraiConsoleImplementationTerminal.kt:81)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.createLoginSolver(MiraiConsoleImplementationBridge.kt:94)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:149)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
        ... 23 more`

**Comment by z594024037** [comment]
mirai-core-all的版本也要用M1-1

**Comment by tdn0102** [comment]
> mirai-core-all的版本也要用M1-1

但我用
`.\mcl --update-package net.mamoe:mirai-core-all --channel nightly --version 2.0-M1-1`
获取更新的时候他给我下的还是M2-4...

**Comment by tdn0102** [comment]
> mirai-core-all的版本也要用M1-1

问题解决，切换mirai-core-all通道到beta就好了
`        "beta": [
            "1.3.1",
            "1.3.3",
            "2.0-M1",
            "2.0-M1-1"
        ],
        "nightly": [
            "1.3.1",
            "1.3.3",
            "2.0-M1-dev-1",
            "2.0-M1-dev-3",
            "2.0-M1",
            "2.0-M1-dev-4",
            "2.0-M1-1",
            "2.0-M2-dev-4"
        ]`

**Comment by GahdWu** [comment]
> "beta": [ "1.3.1", "1.3.3", "2.0-M1", "2.0-M1-1" ], "nightly": [ "1.3.1", "1.3.3", "2.0-M1-dev-1", "2.0-M1-dev-3", "2.0-M1", "2.0-M1-dev-4", "2.0-M1-1", "2.0-M2-dev-4" ]

请问，这个是在哪里设置的？

**Comment by AdorableParker** [comment]
我照着你们说的设置，然后登录的时候报这个是什么问题啊
```
2020-12-29 20:27:30 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2020-12-29 20:27:30 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2020-12-29 20:27:31 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:133)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:56)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-29 20:27:31 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
2020-12-29 20:27:31 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-12-29 20:27:31 W/stderr: Caused by: java.util.jar.JarException: file:/D:/Program%20Files%20(x86)/MiraiProject/mcl-1.0.3/libs/mirai-core-all-2.0-M2.jar has unsigned entries - net/mamoe/mirai/internal/AbstractBot$2.class
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
2020-12-29 20:27:31 W/stderr:   ... 36 more
```

**Comment by dxzenghan** [comment]
> 2.0-M1-1

可以贴一个您用的 config.json 吗 感谢！

**Comment by dxzenghan** [comment]
> > mirai-core-all的版本也要用M1-1
> 
> 问题解决，切换mirai-core-all通道到beta就好了
> ` "beta": [ "1.3.1", "1.3.3", "2.0-M1", "2.0-M1-1" ], "nightly": [ "1.3.1", "1.3.3", "2.0-M1-dev-1", "2.0-M1-dev-3", "2.0-M1", "2.0-M1-dev-4", "2.0-M1-1", "2.0-M2-dev-4" ]`

可以贴一个您用的 config.json 吗 感谢！

**Comment by AdorableParker** [comment]
> 我照着你们说的设置，然后登录的时候报这个是什么问题啊
> 
> ```
> 2020-12-29 20:27:30 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
> 2020-12-29 20:27:30 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
> 2020-12-29 20:27:31 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:133)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:56)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
> 2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 2020-12-29 20:27:31 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 2020-12-29 20:27:31 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:564)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
> 2020-12-29 20:27:31 W/stderr:   at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
> 2020-12-29 20:27:31 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 2020-12-29 20:27:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> 2020-12-29 20:27:31 W/stderr: Caused by: java.util.jar.JarException: file:/D:/Program%20Files%20(x86)/MiraiProject/mcl-1.0.3/libs/mirai-core-all-2.0-M2.jar has unsigned entries - net/mamoe/mirai/internal/AbstractBot$2.class
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
> 2020-12-29 20:27:31 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
> 2020-12-29 20:27:31 W/stderr:   ... 36 more
> ```

emmm。。这个是我没用openJDK的原因

**Comment by openshell** [comment]
各位老哥，知道咋个后台运行吗？ 我运行时加上 &符号，虽然后台运行了，但是QQ没有自动登录。

**Comment by Nambers** [comment]
> 各位老哥，知道咋个后台运行吗？ 我运行时加上 &符号，虽然后台运行了，但是QQ没有自动登录。

设置了自动登录了吗？就mcl设置自动登录命令

**Comment by PeratX** [comment]
自动登录是mirai console的功能
