### ISSUE TITLE
windows下mcl.cmd之后不会运行mirai而是会直接退出

### ISSUE THREAD

**Issue by RiotGamesU** [iTXTech/mirai-console-loader#32]
系统:
Windows Server 2019 Datacenter

mcl版本:
1.0.3

jdk版本:
14.0.2

先是报错:
C:\Users\Administrator\Desktop\mcl-1.0.3>mcl.cmd
 16:06:57 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 16:06:57 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:06:57 [INFO] This program is licensed under GNU AGPL v3
 16:06:57 [DEBUG] Loading script: boot.js
 16:06:57 [DEBUG] Loading script: config.js
 16:06:58 [DEBUG] Loading script: repo.js
 16:06:58 [DEBUG] Loading script: updater.js
 16:06:58 [INFO] Verifying "net.mamoe:mirai-console" version
 16:06:58 [INFO] "net.mamoe:mirai-console:" is corrupted. Start downloading...
 Downloading mirai-console-2.0-M2-dev-4.jar [==============================] 1.66 MB
 Downloading mirai-console-2.0-M2-dev-4.sha1 [==============================] 40 B
 16:07:03 [INFO] Verifying "net.mamoe:mirai-console-terminal" version
 16:07:03 [INFO] "net.mamoe:mirai-console-terminal:" is corrupted. Start downloading...
 Downloading mirai-console-terminal-2.0-M2-dev-4.jar [==============================] 1.24 MB
 Downloading mirai-console-terminal-2.0-M2-dev-4.sha1 [==============================] 40 B
 16:07:05 [INFO] Verifying "net.mamoe:mirai-core-all" version
 16:07:05 [INFO] "net.mamoe:mirai-core-all:" is corrupted. Start downloading...
 Downloading mirai-core-all-1.3.3.jar [==============================] 26.64 MB
 Downloading mirai-core-all-1.3.3.sha1 [==============================] 40 B
java.lang.NoSuchMethodError: 'void net.mamoe.mirai.utils.MiraiLogger$Companion.setDefaultLoggerCreator(kotlin.jvm.functions.Function1)'
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy1.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.MiraiConsole
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy1.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)

把config.json改成如下:
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "nightly",
      "version": "2.0-M2-dev-4",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "nightly",
      "version": "2.0-M2-dev-4",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "nightly",
      "version": "2.0-M2-dev-9",
      "type": "libs"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}

mcl.cmd之后显示:
C:\Users\Administrator\Desktop\mcl-1.0.3>mcl.cmd
 16:12:14 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 16:12:14 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:12:14 [INFO] This program is licensed under GNU AGPL v3
 16:12:14 [DEBUG] Loading script: boot.js
 16:12:14 [DEBUG] Loading script: config.js
 16:12:14 [DEBUG] Loading script: repo.js
 16:12:14 [DEBUG] Loading script: updater.js
 16:12:15 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M1-1
 16:12:15 [INFO] "net.mamoe:mirai-console:2.0-M1-1" is corrupted. Start downloading...
 Downloading mirai-console-2.0-M2-dev-4.jar [==============================] 1.66 MB
 Downloading mirai-console-2.0-M2-dev-4.sha1 [==============================] 40 B
 16:12:19 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M1-1
 16:12:19 [INFO] "net.mamoe:mirai-console-terminal:2.0-M1-1" is corrupted. Start downloading...
 Downloading mirai-console-terminal-2.0-M2-dev-4.jar [==============================] 1.24 MB
 Downloading mirai-console-terminal-2.0-M2-dev-4.sha1 [==============================] 40 B
 16:12:21 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M1-1
 16:12:21 [INFO] "net.mamoe:mirai-core-all:2.0-M1-1" is corrupted. Start downloading...
 Downloading mirai-core-all-2.0-M2-dev-9.jar [==============================] 27.72 MB
 Downloading mirai-core-all-2.0-M2-dev-9.sha1 [==============================] 40 B

随后直接就退出了,再次运行mcl.cmd:
C:\Users\Administrator\Desktop\mcl-1.0.3>mcl.cmd
 16:12:44 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 16:12:44 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:12:44 [INFO] This program is licensed under GNU AGPL v3
 16:12:44 [DEBUG] Loading script: boot.js
 16:12:44 [DEBUG] Loading script: config.js
 16:12:44 [DEBUG] Loading script: repo.js
 16:12:44 [DEBUG] Loading script: updater.js
 16:12:45 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M2-dev-4
 16:12:45 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M2-dev-4
 16:12:46 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M2-dev-9

控制台打印这些信息之后mcl.cmd就退出了,config.json变成了这样:
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "nightly",
      "version": "2.0-M2-dev-4",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "nightly",
      "version": "2.0-M2-dev-4",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "nightly",
      "version": "2.0-M2-dev-9",
      "type": "libs"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}

**Comment by PeratX** [comment]
2.0-M2已发布

**Comment by jinzhijie** [comment]
我也有这种情况

``` powershell
PS >.\mcl
 16:29:00 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 16:29:00 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:29:00 [INFO] This program is licensed under GNU AGPL v3
 16:29:00 [DEBUG] Loading script: boot.js
 16:29:01 [DEBUG] Loading script: config.js
 16:29:01 [DEBUG] Loading script: repo.js
 16:29:01 [DEBUG] Loading script: updater.js
 16:29:02 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M2-1-dev-1
 16:29:03 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M2-1-dev-1
 16:29:03 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.3
java.lang.NoSuchMethodError: 'void net.mamoe.mirai.utils.MiraiLogger$Companion.setDefaultLoggerCreator(kotlin.jvm.functions.Function1)'
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.MiraiConsole
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
```
Java 版本：Liberica JDK 11
``` powershell
PS >java -version
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-LTS, mixed mode)
```

**Comment by Cicini** [comment]
同
目前在Debian 10 (openjdk 11.0.7)和Windows Server 2019 (openjdk 11 14和 java8)都试过了
也是这样的报错

**Comment by PeratX** [comment]
.\mcl --update-package net.mamoe:mirai-core-all --channel nightly
