### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jerrita** [iTXTech/mirai-console-loader#36]
root@0513d622921b:/work# ls
LICENSE  README.md  mcl  mcl.cmd  mcl.jar  scripts
root@0513d622921b:/work# ./mcl
bash: ./mcl: Permission denied
root@0513d622921b:/work# chmod +x mcl
root@0513d622921b:/work# ./mcl 
 09:24:56 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 09:24:56 [INFO] https://github.com/iTXTech/mirai-console-loader
 09:24:56 [INFO] This program is licensed under GNU AGPL v3
 09:24:56 [DEBUG] Loading script: boot.js
 09:24:57 [DEBUG] Loading script: config.js
 09:24:57 [DEBUG] Loading script: repo.js
 09:24:57 [DEBUG] Loading script: updater.js
 09:24:57 [INFO] Verifying "net.mamoe:mirai-console" version 
 09:24:57 [INFO] "net.mamoe:mirai-console:" is corrupted. Start downloading...
 Downloading mirai-console-2.0-M2.jar [==============================] 1.67 MB                         
 Downloading mirai-console-2.0-M2.sha1 [==============================] 40 B                  
 09:25:01 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 
 09:25:01 [INFO] "net.mamoe:mirai-console-terminal:" is corrupted. Start downloading...
 Downloading mirai-console-terminal-2.0-M2.jar [==============================] 1.24 MB                         
 Downloading mirai-console-terminal-2.0-M2.sha1 [==============================] 40 B                  
 09:25:03 [INFO] Verifying "net.mamoe:mirai-core-all" version 
 09:25:03 [INFO] "net.mamoe:mirai-core-all:" is corrupted. Start downloading...
 Downloading mirai-core-all-1.3.3.jar [==============================] 26.64 MB                        
 Downloading mirai-core-all-1.3.3.sha1 [==============================] 40 B                  
java.lang.NoSuchMethodError: 'void net.mamoe.mirai.utils.MiraiLogger$Companion.setDefaultLoggerCreator(kotlin.jvm.functions.Function1)'
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy1.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:128)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.MiraiConsole
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy1.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:128)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
root@0513d622921b:/work# ls
LICENSE  README.md  config  config.json  data  libs  mcl  mcl.cmd  mcl.jar  scripts

**Comment by 435qb** [comment]
有解决方法了吗，我的也是这个问题
