### ISSUE TITLE
kotlin.UninitializedPropertyAccessException异常

### ISSUE THREAD

**Issue by charlotte-xiao** [iTXTech/mirai-console-loader#55]
2021-02-09 18:31:19 E/console: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
        at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:118)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:176)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand$handle$1.invokeSuspend(BuiltInCommands.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by PeratX** [comment]
请反馈到mirai并提供完整日志。
mcl只负责下载和启动mirai，启动后的一切报错几乎和mcl无关。
