### ISSUE TITLE
自动登录报错

### ISSUE THREAD

**Issue by RiotGamesU** [iTXTech/mirai-console-loader#7]
root@debian:~/mirai# sh mcl
 15:07:21 [INFO] Mirai Console Loader version 1.0.1-b322e99
 15:07:21 [INFO] https://github.com/iTXTech/mirai-console-loader
 15:07:21 [INFO] This program is licensed under GNU AGPL v3
 15:07:21 [DEBUG] Loading script: updater.js
 15:07:22 [DEBUG] Loading script: config.js
 15:07:22 [DEBUG] Loading script: boot.js
 15:07:22 [INFO] Verifying "net.mamoe:mirai-console" version 1.0-RC-dev-32
 15:07:23 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 1.0-RC-dev-32
 15:07:23 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.1
2020-10-29 15:07:24 I/main: Starting mirai-console...
2020-10-29 15:07:24 I/main: Backend: version 1.0-RC-dev-32, built on 2020-10-24 21:56:55.
2020-10-29 15:07:24 I/main: Frontend Terminal: version 1.0-RC-dev-32, provided by Mamoe Technologies
2020-10-29 15:07:24 V/main: Loading configurations...
2020-10-29 15:07:25 V/main: Loading JVM plugins...
2020-10-29 15:07:25 V/main: 0 external PluginLoader(s) found. 
2020-10-29 15:07:25 V/main: 0 plugin(s) loaded.
2020-10-29 15:07:25 V/main: Loading PermissionService...
2020-10-29 15:07:25 V/main: Reloaded PermissionService settings.
2020-10-29 15:07:25 V/main: Loading built-in commands...
2020-10-29 15:07:25 V/main: Prepared built-in commands: help, login, permission, stop
2020-10-29 15:07:25 V/main: Enabling plugins...
2020-10-29 15:07:25 I/main: 0 plugin(s) enabled.
2020-10-29 15:07:25 I/main: Auto-login 1111111111
2020-10-29 15:07:26 I/Bot 1111111111: Logging in...
2020-10-29 15:07:27 I/Bot 1111111111: Login successful
2020-10-29 15:07:27 I/main: Auto-login 2222222222
2020-10-29 15:07:27 I/Bot 2222222222: Logging in...
 15:07:27 [ERROR] org.mozilla.javascript.WrappedException: Wrapped net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=) (boot.js#74)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at script(boot.js:74)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:125)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:201)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:192)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:154)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 18 more

^C2020-10-29 15:07:41 I/Bot 1111111111: Bot cancelled: Job was cancelled

**Comment by RiotGamesU** [comment]
环境
os
root@debian:~/mirai# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

jdk
root@debian:~/mirai# apt install default-jdk
root@debian:~/mirai# java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)
root@debian:~/mirai# javac -version
javac 11.0.9


补充
1.刚刚下载的最新版
2.第一次运行正常
3.第一次运行到一半的时候断网了(一半的时候断网指 自动登录的配置文件里添加了多个账号 正在输入验证码和手机QQ扫码验证的过程中断开了) xshell连接断了 现在重新连上之后就一直报这个错误(不知道和xshell断连有没有关系>_<)

**Comment by PeratX** [comment]
请向`mirai core`团队汇报
