### ISSUE TITLE
MCL无法启动 Failed to verify package "org.itxtech:mcl-addon"

### ISSUE THREAD

**Issue by asforest** [iTXTech/mirai-console-loader#85]
重启Miral后就再也无法启动了，一直报错`Failed to verify package "org.itxtech:mcl-addon"`，多次尝试也还是会这样

JDK是java11
```
orangepi@orangepizero:~/mcl-1.2.2$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2deb10u1)
OpenJDK Server VM (build 11.0.12+7-post-Debian-2deb10u1, mixed mode)
```

错误信息：

```
orangepi@orangepizero:~/mcl-1.2.2$ /usr/bin/java -jar mcl.jar
  14:51:45 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  14:51:45 [INFO] https://github.com/iTXTech/mirai-console-loader
  14:51:45 [INFO] This program is licensed under GNU AGPL v3
  14:51:51 [INFO] Fetching Mirai Console Loader Announcement...
  14:51:57 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

关于 Bot is closed manually
https://mirai.mamoe.net/topic/604/

  14:51:57 [INFO] Verifying "net.mamoe:mirai-console" v2.7.1-dev-1
  14:51:57 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.7.1-dev-1
  14:51:58 [INFO] Verifying "net.mamoe:mirai-core-all" v2.7.1-dev-1
  14:52:00 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  14:52:00 [ERROR] Failed to verify package "org.itxtech:mcl-addon"
  14:52:00 [ERROR] java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.lang.StringCoding.throwMalformed(StringCoding.java:685)
        at java.base/java.lang.StringCoding.decodeUTF8_0(StringCoding.java:872)
        at java.base/java.lang.StringCoding.newStringNoRepl1(StringCoding.java:1005)
        at java.base/java.lang.StringCoding.newStringNoRepl(StringCoding.java:990)
        at java.base/java.lang.System$2.newStringNoRepl(System.java:2197)
        at java.base/java.nio.file.Files.readString(Files.java:3287)
        at java.base/java.nio.file.Files.readString(Files.java:3243)
        at org.itxtech.mcl.Utility.check(Utility.java:62)
        at org.itxtech.mcl.Utility.checkLocalFile(Utility.java:69)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:98)
        at org.itxtech.mcl.Loader.lambda$start$2(Loader.java:172)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:172)
        at org.itxtech.mcl.Loader.main(Loader.java:68)

orangepi@orangepizero:~/mcl-1.2.2$
```

**Comment by asforest** [comment]
重新配置了MCL后似乎能正常启动了

**Comment by asforest** [comment]
找到具体原因了，`config/Console/Logger.yml`文件不知道什么原因内容是乱码的，删除后就能正常启动了
