### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by m00nfly** [iTXTech/mirai-console-loader#87]
**java环境：**
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

**执行mcl 报错退出**

`18:38:07 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
 18:38:07 [INFO] https://github.com/iTXTech/mirai-console-loader
 18:38:07 [INFO] This program is licensed under GNU AGPL v3
 18:38:08 [INFO] MCL Addon is installed! Website: https://github.com/iTXTech/mcl-addon
 18:38:08 [WARN] To remove MCL Addon, run "./mcl --disable-script addon" and "./mcl --remove-package org.itxtech:mcl-addon --delete"
 18:38:08 [INFO] BouncyCastle is installed because OracleJDK is detected.
 18:38:08 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v
 18:38:08 [ERROR] "org.bouncycastle:bcprov-jdk15on" is corrupted.
 18:38:08 [ERROR] Failed to verify package "org.bouncycastle:bcprov-jdk15on"
 18:38:08 [ERROR] java.net.ConnectException
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:555)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:128)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`

根据提示也执行过 `./mcl --remove-package org.itxtech:mcl-addon --delete` 了还是无法正常启动

**Comment by PeratX** [comment]
请检查网络连接
