### ISSUE TITLE
debian下输入help报错

### ISSUE THREAD

**Issue by RiotGamesU** [iTXTech/mirai-console-loader#9]
mirai-console-loader下
输入 > help
2020-10-30 12:29:22 E/console: java.lang.IllegalArgumentException: No argument provided for a required parameter: extension receiver parameter of fun net.mamoe.mirai.console.command.BuiltInCommands.HelpCommand.(net.mamoe.mirai.console.command.CommandSender.)handle(): kotlin.Unit
java.lang.IllegalArgumentException: No argument provided for a required parameter: extension receiver parameter of fun net.mamoe.mirai.console.command.BuiltInCommands.HelpCommand.(net.mamoe.mirai.console.command.CommandSender.)handle(): kotlin.Unit
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:145)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$5$1.invokeSuspend(CommandReflector.kt:221)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$5$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureVariantFromKFunctionImpl.call$suspendImpl(CommandDescriptor.kt:79)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureVariantFromKFunctionImpl.call(CommandDescriptor.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:184)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

环境
os
root@debian:~/mirai# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

jdk
root@debian:~/mirai# apt install default-jdk

root@debian:~/mirai# java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.9+11-post-Debian-1deb10u1, mixed mode, sharing)

root@debian:~/mirai# javac -version
javac 11.0.9

**Comment by dousha** [comment]
这应该是来自 `mirai-console` 的不兼容变更。目前的 workaround 是降级 `mirai-console` 和 `mirai-console-terminal` 到 `1.0-RC-dev-29`.

**Comment by PeratX** [comment]
考虑是`mirai-console`的问题，`loader`在`boot console`后不再处理任何操作
