### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Ljzd-PRO** [iTXTech/mirai-console-loader#90]
```
  10:54:02 [INFO] Verifying "net.mamoe:mirai-console" v2.8.0
  10:54:04 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.8.0
  10:54:04 [INFO] Verifying "net.mamoe:mirai-core-all" v2.8.0
  10:54:04 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  10:54:05 [INFO] Verifying "net.mamoe:mirai-api-http" v1.10.0
  10:54:05 [INFO] Verifying "org.itxtech:mirai-native" v1.9.6
  10:54:05 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  10:54:05 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.lang.StringIndexOutOfBoundsException: start -2, end 0, length 0 (boot.js#98)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script(boot.js:98)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:176)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:145)
        at org.itxtech.mcl.Loader.start(Loader.java:176)
        at org.itxtech.mcl.Loader.main(Loader.java:68)
Caused by: java.lang.StringIndexOutOfBoundsException: start -2, end 0, length 0
        at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(Unknown Source)
        at java.base/java.lang.AbstractStringBuilder.delete(Unknown Source)
        at java.base/java.lang.StringBuilder.delete(Unknown Source)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 20 more
```

**Comment by PeratX** [comment]
检查下是否有自定义的启动参数

**Comment by Ljzd-PRO** [comment]
用macOS和Linux都可以正常使用，这个是Windows出现的，之后也没有再用Windows测试了
