### ISSUE TITLE
MCL无法启动

### ISSUE THREAD

**Issue by Cybercll** [iTXTech/mirai-console-loader#97]
以下为启动日志
`
12:05:07 [INFO] Fetching Mirai Console Loader Announcement...
  12:05:10 [ERROR] Failed to fetch announcement.
  12:05:10 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
  12:05:10 [ERROR] Failed to verify package "net.mamoe:mirai-console"
  12:05:10 [ERROR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMet.....
`

**Comment by PeratX** [comment]
检查网络问题

**Comment by Cybercll** [comment]
> 检查网络问题

我本地测试没有问题但在Oracle cloud服务器上却显示此错误 ip 146.56.117.* 地址位于韩国
方便提供下公告等服务连接的域名吗 我可以测试下是什么问题

**Comment by Cybercll** [comment]
> 检查网络问题

是gitee的问题，gitee屏蔽了其他服务器访问raw文件，而公告和其他文件都是通过raw进行访问的，故会无法获取公告和校验文件
再问下如何切换到github呢，海外大部分服务器访问gitee的raw时都会返回403

**Comment by PeratX** [comment]
https://raw.githubusercontent.com/project-mirai/mirai-repo-mirror/master/
